encrypt-dir: fix passphrase prompt interrupting progress report

diff --git a/home/local/bin/encrypt-dir b/home/local/bin/encrypt-dir
--- a/home/local/bin/encrypt-dir
+++ b/home/local/bin/encrypt-dir
@@ -1,19 +1,26 @@
 #!/usr/bin/env bash
 
+PROGRAM="$(basename "${0}")"
+
 if ((${BASH_VERSION%%.*} < 4)); then
-	echo "$(basename "${0}") requires Bash version 4 or later" 1>&2
+	echo "${PROGRAM}: requires Bash version 4 or later" >&2
 	exit 1
 fi
 
 set -euo pipefail
 
 if ! [ "$#" -eq 1 ]; then
-	echo "$(basename "${0}"): expecting a single argument with the directory path"
+	echo "${PROGRAM}: expecting a single argument with the directory path" >&2
 	exit 1
 fi
 
-if ! [ -x "$(command -v mcrypt)" ]; then
-	echo 'mcrypt not found' 1>&2
+if ! [ -x "$(command -v gpg)" ]; then
+	echo "${PROGRAM}: gpg not found" >&2
+	exit 1
+fi
+
+if ! [ -x "$(command -v pv)" ]; then
+	echo "${PROGRAM}: pv not found" >&2
 	exit 1
 fi
 
@@ -23,24 +30,39 @@ DIR_PATH="${PARENT_DIR}/${DIR_NAME}"
 OUTPUT_PATH="$(basename "${DIR_NAME}").tar.gz.gpg"
 
 if ! [ -d "${DIR_PATH}" ]; then
-	echo "$(basename "${0}"): ${DIR_PATH} is not a directory" 1>&2
+	echo "${PROGRAM}: ${DIR_PATH} is not a directory" >&2
 	exit 1
 fi
 
-DIR_SIZE="$(du -hs "${DIR_PATH}" | cut -f -1 || true)"
+DIR_SIZE="$(du -hs "${DIR_PATH}" | cut -f -1 || echo 'Unknown size')"
 
-echo "Encrypting directory ${DIR_PATH} (${DIR_SIZE})"
+echo "Encrypting directory ${DIR_PATH} (${DIR_SIZE})" >&2
+
+read -s -p "Enter passphrase: " passphrase
+echo
+read -s -p "Repeat passphrase: " passphrase_repeat
+echo
+if ! [ "${passphrase}" = "${passphrase_repeat}" ]; then
+	echo "${PROGRAM}: passphrases do not match" >&2
+	exit 1
+fi
+unset passphrase_repeat
 
 tar \
-	--directory "${PARENT_DIR}/" \
+	--create --gzip --format=posix \
+	--preserve-permissions --same-owner \
 	--ignore-failed-read \
-	--create --gzip "${DIR_NAME}" \
-	| pv \
+	--directory "${PARENT_DIR}/" \
+	--to-stdout "${DIR_NAME}" \
+	| pv --wait --delay-start 2 \
 	| gpg \
-	--pinentry-mode loopback \
 	--symmetric \
+	--pinentry-mode loopback \
+	--passphrase "${passphrase}" \
 	--output "${OUTPUT_PATH}"
+
+unset passphrase
 
 OUTPUT_SIZE="$(du -h "${OUTPUT_PATH}" | cut -f -1)"
 
-echo "Wrote encrypted archive to ${OUTPUT_PATH} (${OUTPUT_SIZE})"
+echo "Wrote encrypted archive to ${OUTPUT_PATH} (${OUTPUT_SIZE})" >&2
